### ISSUE TITLE
What do IS IU LD mean？

### ISSUE THREAD

**Issue by longyunyun** [SimoneRichetti/VRPTW-Column-Generation#1]
Hello I can't understand why ISIULD is calculated here. What do IS IU LD mean？

def computeISIULD(posU, route, arr, s, a, b, d, Jminu):
    u = route[posU]
    posI = posU-1; posJ = posU+1
    i = route[posI]; j = route[posJ]
    IS = arr[posU] - a[u]
    IU = 1/(max([len(Jminu), 1])) * sum([max([b[n]-a[u]-d[u,n], b[u]-a[n]-d[u,n]]) \
                                for n in Jminu])
    c1 = (d[i,u] + d[u,j] - d[i,j])
    c2 = ((b[j]- (arr[posI] + d[i,j])) - \
                (b[j] - (arr[posU] + d[i,j])))
    c3 = (b[u] - (arr[posI] + d[i,u]))
    LD = b1*c1 + b2*c2 + b3*c3
    print("IS IU LD")
    print(IS)
    print(IU)
    print(LD)
    return IS, IU, LD

**Comment by SimoneRichetti** [comment]
Hi @longyunyun! Thank you for your question. I cite you the paper that explains the algorithm (I implemented it in the same way it is explained):

![image](https://user-images.githubusercontent.com/17830731/79886915-28ee7400-83fa-11ea-8e82-c725f61570b3.png)
![image](https://user-images.githubusercontent.com/17830731/79886931-31df4580-83fa-11ea-9579-c6933b296d6c.png)

You will use these quantities later to compute the impact value. that you use to find the best position in which insert the related customer.

The paper is:
[M. K. a. G. P. G Ioannou, «A greedy look-ahead heuristic for the vehicle routing,» Journal of the
Operational Research Society, 2001.](https://www.researchgate.net/publication/233699519_A_greedy_look-ahead_heuristic_for_the_vehicle_routing_problem_with_time_windows)

I recommend you to read the paper, I found it quite easy to read, understand and implement.
