### ISSUE TITLE
subProblem resolution

### ISSUE THREAD

**Issue by French988** [SimoneRichetti/VRPTW-Column-Generation#2]
Hi, can you please tell me where did you take your dynamic algorithm for the subproblem? Thanks in advance

**Comment by SimoneRichetti** [comment]
Hi @French988,
sorry for the huge delay. I have added a reference section in the README file.
I think that the algorithm for the subproblem was thought to us by the professor during the lectures, but, if I remember well, part of the references were suggested by the professor itself, and I hope you can find the algorithm there.
